crumble/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('notes/', include('notes.urls')),
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
    path('', views.my_note, name="my-note"),
    path('new-note/', views.note_new, name="new-note"),
    path('<slug:slug>', views.note_page, name="page"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('new-post/', views.post_new, name="new-post"),
    path('<slug:slug>', views.post_page, name="page"),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_page, name="register"),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('profile/my-profile', views.profile_page, name='profile'),
    path('profile/my-notes', views.profile_notes_page, name='notes'),
    path('<str:username>/follow/', views.follow_user, name='follow'),
    path('<str:username>/unfollow/', views.unfollow_user, name='unfollow'),
    path('toggle/<str:username>/', views.toggle_follow_user, name='toggle_follow_user'),
    path('togglermv/<str:username>/', views.rmv_follower, name='rmv_follower'),
    path('<str:username>/', views.other_user_profile, name='other_profile'),
    path('<str:username>/followers/', views.FollowersView.as_view(), name='followers'),
    path('<str:username>/following/', views.FollowingView.as_view(), name='following'),
]

templates/about.html
{% extends 'layout.html' %}

{% block title %}
  	About
{% endblock%}

{% block content %}
	<h1>About</h1>
	<p>Check out my <a href="/">Home</a> page.</p>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock%}

{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>
			{% block title %} 
				Django App 
			{% endblock %}
		</title>
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		<script src="{% static 'js/main.js' %}" defer></script>
	</head>
	<body>
		<nav>
			<div class="heading-container">
				<a href="/">
					<span class="home-heading" role="heading" aria-label="Home" title="Home">
						Crumble
					</span>
				</a>
			</div>
			<a class="a-element" href="/">
				<span role="img" aria-label="Home" title="Home">
					<img src="{% static 'icons/home.png' %}" defer>
					<p>Home</p>
				</span>
			</a> 
			{% if user.is_authenticated %}
				<a class="a-element-a" href="{% url 'users:profile' %}">
					<span role="img" aria-label="Profile" title="Profile">
						<img src="{{ user.profile.image.url }}" defer>
						<p>Profile</p>
					</span>
				</a>
			{% endif %}
				<a class="a-element" href="{% url 'posts:list' %}">
					<span role="img" aria-label="Posts" title="Posts">
						<img src="{% static 'icons/play.png' %}" defer> 
						<p>Posts</p>
					</span>
				</a>
			{% if user.is_authenticated %}
				<a class="a-element" href="{% url 'posts:new-post' %}">
					<span role="img" aria-label="Upload Post" title="Upload Post">
						<img src="{% static 'icons/picture.png' %}" defer>
						<p>Post</p>
					</span>
				</a>
				<a class="a-element" href="{% url 'notes:new-note' %}">
					<span role="img" aria-label="Upload Note" title="Upload Note">
						<img src="{% static 'icons/book-alt.png' %}" defer>
						<p>Note</p>
					</span>
				</a>
				</div>
				<form class="a-element" action="{% url 'users:logout' %}" method="post">
					{% csrf_token %}
					<button class="logout" aria-label="User Logout" title="User Logout">
						<img src="{% static 'icons/sign-out-alt.png' %}"defer>
						<p>Logout</p>
					</button>
				</form>
			{% else %}
				<a class="a-element" href="{% url 'users:register' %}">
					<span role="img" aria-label="Register" title="Register">
						<img src="{% static 'icons/user.png' %}" defer>
						<p>Register</p>
					</span>
				</a>
				<a class="a-element" href="{% url 'users:login' %}">
					<span role="img" aria-label="Login" title="Login">
						<img src="{% static 'icons/lock.png' %}" defer>
						<p>Login</p>
					</span>
				</a> 
			{% endif %}
		</nav>
		<main>
			{% block content %} 
			{% endblock %}
		</main>
	</body>
</html>